def git_url = 'https://github.com/intelligaia/react-big-calendar.git'
def git_branch = 'V1'

pipeline
{
    agent
    {
        label 'teza.projectsjunction'
    }

    stages
    {
        stage('build-code')
        {
            
            steps{
                   sh '''
                   pwd
                   npm install
                   npm run build
                   '''
            }
        }
        stage('copy-build')
        {
            
            steps{
                   sh '''
                   ls
                   pwd
                   rsync -parv build /home/ubuntu/react-big-calendar
                   '''
            }
        }
        stage('app-restart'){ 
            steps{
                   sh '''
                   sudo systemctl restart nginx
                   '''
            }
        }
    }
}
